// <auto-generated />
using BodegaDESAM;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BodegaDESAM.Data.Migrations
{
    [DbContext(typeof(PostgresDataContext))]
    [Migration("20260922170000_AddValorUnitario")]
    partial class AddValorUnitario
    {
    }
}
