// <auto-generated />
using System;
using BodegaDESAM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BodegaDESAM.Data.Migrations
{
    [DbContext(typeof(PostgresDataContext))]
    [Migration("20260922150425_AddAlertaStockPorBodega")]
    partial class AddAlertaStockPorBodega
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BodegaDESAM")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BodegaDESAM.AjusteInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("id_bodega")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_bodega");

                    b.ToTable("ajuste_inventario", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.AlertaStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBodega")
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("stock_minimo");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdBodega", "IdProducto")
                        .IsUnique();

                    b.ToTable("alerta_stock", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying")
                        .HasColumnName("codigo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("direccion");

                    b.Property<bool>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_principal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("bodega", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.CategoriaProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categoria_producto", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleAjuste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Cantidad")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TipoAjuste")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_ajuste")
                        .HasColumnType("integer");

                    b.Property<int?>("id_detalle_ajuste_origen")
                        .HasColumnType("integer");

                    b.Property<int?>("id_detalle_entrada_origen")
                        .HasColumnType("integer");

                    b.Property<long?>("id_lote")
                        .HasColumnType("bigint");

                    b.Property<long>("id_marca")
                        .HasColumnType("bigint");

                    b.Property<long?>("id_modelo")
                        .HasColumnType("bigint");

                    b.Property<int>("id_producto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_ajuste");

                    b.HasIndex("id_detalle_ajuste_origen");

                    b.HasIndex("id_detalle_entrada_origen");

                    b.HasIndex("id_lote");

                    b.HasIndex("id_marca");

                    b.HasIndex("id_modelo");

                    b.HasIndex("id_producto");

                    b.ToTable("detalle_ajuste", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Cantidad")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("id_entrada")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_entrada");

                    b.Property<long?>("id_lote")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    b.Property<long>("id_marca")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    b.Property<long?>("id_modelo")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_modelo");

                    b.Property<int>("id_producto")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<long?>("id_ubicacion")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("id_entrada");

                    b.HasIndex("id_lote");

                    b.HasIndex("id_marca");

                    b.HasIndex("id_modelo");

                    b.HasIndex("id_producto");

                    b.HasIndex("id_ubicacion");

                    b.ToTable("detalle_entrada", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int?>("id_detalle_ajuste_origen")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_ajuste_origen");

                    b.Property<int?>("id_detalle_entrada")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_entrada");

                    b.Property<long?>("id_lote")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_lote");

                    b.Property<long>("id_marca")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    b.Property<long?>("id_modelo")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_modelo");

                    b.Property<int>("id_producto")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int>("id_salida")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_salida");

                    b.Property<long?>("id_ubicacion")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("id_detalle_ajuste_origen");

                    b.HasIndex("id_detalle_entrada");

                    b.HasIndex("id_lote");

                    b.HasIndex("id_marca");

                    b.HasIndex("id_modelo");

                    b.HasIndex("id_producto");

                    b.HasIndex("id_salida");

                    b.HasIndex("id_ubicacion");

                    b.ToTable("detalle_salida", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("n_documento");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("observacion");

                    b.Property<int>("id_bodega")
                        .HasColumnType("integer");

                    b.Property<int>("id_proveedor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_bodega");

                    b.HasIndex("id_proveedor");

                    b.ToTable("entrada", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Establecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("establecimiento", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Lote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaFabricacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fabricacion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("observaciones");

                    b.Property<int>("id_producto")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("id_producto", "Codigo")
                        .IsUnique();

                    b.ToTable("lote", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Marca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("marca", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Modelo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_marca")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    b.HasKey("Id");

                    b.HasIndex("id_marca", "Nombre")
                        .IsUnique();

                    b.ToTable("modelo", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_categoria_producto")
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_producto");

                    b.HasKey("Id");

                    b.HasIndex("id_categoria_producto");

                    b.ToTable("producto", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.ProductoSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("serie");

                    b.Property<int?>("id_detalle_ajuste")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_ajuste");

                    b.Property<int?>("id_detalle_entrada")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_entrada");

                    b.Property<int>("id_producto")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<int?>("id_salida")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_salida");

                    b.HasKey("Id");

                    b.HasIndex("id_detalle_ajuste");

                    b.HasIndex("id_detalle_entrada");

                    b.HasIndex("id_salida");

                    b.HasIndex("id_producto", "Serie")
                        .IsUnique();

                    b.ToTable("producto_serie", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<string>("PersonaContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("persona_contacto");

                    b.Property<string>("RUT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying")
                        .HasColumnName("rut");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("proveedor", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("observacion");

                    b.Property<string>("Solicitante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying")
                        .HasColumnName("solicitante");

                    b.Property<int>("id_bodega")
                        .HasColumnType("integer");

                    b.Property<int>("id_establecimiento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_bodega");

                    b.HasIndex("id_establecimiento");

                    b.ToTable("salida", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.Ubicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Bloqueada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("bloqueada");

                    b.Property<decimal?>("CapacidadMaxima")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("capacidad_maxima");

                    b.Property<string>("CodigoCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying")
                        .HasColumnName("codigo_completo");

                    b.Property<string>("Estante")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying")
                        .HasColumnName("estante");

                    b.Property<string>("MotivoBloqueo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying")
                        .HasColumnName("motivo_bloqueo");

                    b.Property<string>("Nivel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying")
                        .HasColumnName("nivel");

                    b.Property<string>("Pasillo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying")
                        .HasColumnName("pasillo");

                    b.Property<string>("Posicion")
                        .HasMaxLength(10)
                        .HasColumnType("character varying")
                        .HasColumnName("posicion");

                    b.Property<int>("id_bodega")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_bodega", "CodigoCompleto")
                        .IsUnique();

                    b.ToTable("ubicacion", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.UsuarioBodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBodega")
                        .HasColumnType("integer")
                        .HasColumnName("id_bodega");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("IdBodega");

                    b.HasIndex("IdUsuario", "IdBodega")
                        .IsUnique();

                    b.ToTable("usuario_bodega", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "BodegaDESAM");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "BodegaDESAM");
                });

            modelBuilder.Entity("BodegaDESAM.AjusteInventario", b =>
                {
                    b.HasOne("BodegaDESAM.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("id_bodega")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bodega");
                });

            modelBuilder.Entity("BodegaDESAM.AlertaStock", b =>
                {
                    b.HasOne("BodegaDESAM.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleAjuste", b =>
                {
                    b.HasOne("BodegaDESAM.AjusteInventario", "Ajuste")
                        .WithMany("DetalleAjuste")
                        .HasForeignKey("id_ajuste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.DetalleAjuste", "DetalleAjusteOrigen")
                        .WithMany("DisminucionesOrigen")
                        .HasForeignKey("id_detalle_ajuste_origen")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.DetalleEntrada", "DetalleEntradaOrigen")
                        .WithMany()
                        .HasForeignKey("id_detalle_entrada_origen")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("id_lote")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("id_modelo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ajuste");

                    b.Navigation("DetalleAjusteOrigen");

                    b.Navigation("DetalleEntradaOrigen");

                    b.Navigation("Lote");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleEntrada", b =>
                {
                    b.HasOne("BodegaDESAM.Entrada", "Entrada")
                        .WithMany("DetalleEntrada")
                        .HasForeignKey("id_entrada")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Lote", "Lote")
                        .WithMany("DetalleEntradas")
                        .HasForeignKey("id_lote")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Marca", "Marca")
                        .WithMany("DetalleEntradas")
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Modelo", "Modelo")
                        .WithMany("DetalleEntradas")
                        .HasForeignKey("id_modelo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Producto", "Producto")
                        .WithMany("DetalleEntrada")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Ubicacion", "Ubicacion")
                        .WithMany("DetalleEntradas")
                        .HasForeignKey("id_ubicacion")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Entrada");

                    b.Navigation("Lote");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("Producto");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleSalida", b =>
                {
                    b.HasOne("BodegaDESAM.DetalleAjuste", "DetalleAjusteOrigen")
                        .WithMany()
                        .HasForeignKey("id_detalle_ajuste_origen")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.DetalleEntrada", "DetalleEntrada")
                        .WithMany("DetalleSalidas")
                        .HasForeignKey("id_detalle_entrada")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Lote", "Lote")
                        .WithMany("DetalleSalidas")
                        .HasForeignKey("id_lote")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("id_modelo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Producto", "Producto")
                        .WithMany("DetalleSalida")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Salida", "Salida")
                        .WithMany("DetalleSalida")
                        .HasForeignKey("id_salida")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Ubicacion", "Ubicacion")
                        .WithMany("DetalleSalidas")
                        .HasForeignKey("id_ubicacion")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DetalleAjusteOrigen");

                    b.Navigation("DetalleEntrada");

                    b.Navigation("Lote");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("Producto");

                    b.Navigation("Salida");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("BodegaDESAM.Entrada", b =>
                {
                    b.HasOne("BodegaDESAM.Bodega", "Bodega")
                        .WithMany("Entradas")
                        .HasForeignKey("id_bodega")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Proveedor", "Proveedor")
                        .WithMany("Entrada")
                        .HasForeignKey("id_proveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BodegaDESAM.Lote", b =>
                {
                    b.HasOne("BodegaDESAM.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaDESAM.Modelo", b =>
                {
                    b.HasOne("BodegaDESAM.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("BodegaDESAM.Producto", b =>
                {
                    b.HasOne("BodegaDESAM.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("id_categoria_producto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CategoriaProducto");
                });

            modelBuilder.Entity("BodegaDESAM.ProductoSerie", b =>
                {
                    b.HasOne("BodegaDESAM.DetalleAjuste", "DetalleAjuste")
                        .WithMany()
                        .HasForeignKey("id_detalle_ajuste")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.DetalleEntrada", "DetalleEntrada")
                        .WithMany("ProductoSeries")
                        .HasForeignKey("id_detalle_entrada")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BodegaDESAM.Producto", "Producto")
                        .WithMany("ProductoSeries")
                        .HasForeignKey("id_producto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Salida", "Salida")
                        .WithMany("ProductoSeries")
                        .HasForeignKey("id_salida")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DetalleAjuste");

                    b.Navigation("DetalleEntrada");

                    b.Navigation("Producto");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BodegaDESAM.Salida", b =>
                {
                    b.HasOne("BodegaDESAM.Bodega", "Bodega")
                        .WithMany("Salidas")
                        .HasForeignKey("id_bodega")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BodegaDESAM.Establecimiento", "EStablecimiento")
                        .WithMany("Salida")
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("EStablecimiento");
                });

            modelBuilder.Entity("BodegaDESAM.Ubicacion", b =>
                {
                    b.HasOne("BodegaDESAM.Bodega", "Bodega")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("id_bodega")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bodega");
                });

            modelBuilder.Entity("BodegaDESAM.UsuarioBodega", b =>
                {
                    b.HasOne("BodegaDESAM.Bodega", "Bodega")
                        .WithMany()
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BodegaDESAM.AjusteInventario", b =>
                {
                    b.Navigation("DetalleAjuste");
                });

            modelBuilder.Entity("BodegaDESAM.Bodega", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Salidas");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("BodegaDESAM.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleAjuste", b =>
                {
                    b.Navigation("DisminucionesOrigen");
                });

            modelBuilder.Entity("BodegaDESAM.DetalleEntrada", b =>
                {
                    b.Navigation("DetalleSalidas");

                    b.Navigation("ProductoSeries");
                });

            modelBuilder.Entity("BodegaDESAM.Entrada", b =>
                {
                    b.Navigation("DetalleEntrada");
                });

            modelBuilder.Entity("BodegaDESAM.Establecimiento", b =>
                {
                    b.Navigation("Salida");
                });

            modelBuilder.Entity("BodegaDESAM.Lote", b =>
                {
                    b.Navigation("DetalleEntradas");

                    b.Navigation("DetalleSalidas");
                });

            modelBuilder.Entity("BodegaDESAM.Marca", b =>
                {
                    b.Navigation("DetalleEntradas");
                });

            modelBuilder.Entity("BodegaDESAM.Modelo", b =>
                {
                    b.Navigation("DetalleEntradas");
                });

            modelBuilder.Entity("BodegaDESAM.Producto", b =>
                {
                    b.Navigation("DetalleEntrada");

                    b.Navigation("DetalleSalida");

                    b.Navigation("ProductoSeries");
                });

            modelBuilder.Entity("BodegaDESAM.Proveedor", b =>
                {
                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("BodegaDESAM.Salida", b =>
                {
                    b.Navigation("DetalleSalida");

                    b.Navigation("ProductoSeries");
                });

            modelBuilder.Entity("BodegaDESAM.Ubicacion", b =>
                {
                    b.Navigation("DetalleEntradas");

                    b.Navigation("DetalleSalidas");
                });
#pragma warning restore 612, 618
        }
    }
}
